### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by martinjoiner** [martinjoiner/Skywriter-WebGL#1]
- [x] Strip out the Node.js stuff, this is an improper use of it. Focus the project on WebGL.
 - [x] Skypmap to look more like sky
 - [x] Improve plane to look more like a plane
 - [x] Ability to enable/disable smoker
 - [x] Basic white noise to accompany smoker on
 - [ ] Build basic controls to fly the plane: Pull back / push forward / throttle / start smoke / stop smoke 
 - [ ] Sound FX for engine under different loads 
 - [ ] Training mode to teach the "pilot" how to draw each letter
